const API_BASE='https://lifemoney-api-production.up.railway.app';
const qs=(s)=>document.querySelector(s); const qsa=(s)=>[...document.querySelectorAll(s)];
const money=(n)=>{n=Number(n)||0;const a=Math.abs(n);if(a>=10000000)return `₹${(n/10000000).toFixed(a>=100000000?1:2)} Cr`;if(a>=100000)return `₹${(n/100000).toFixed(a>=1000000?1:2)} L`;return `₹${Math.round(n).toLocaleString('en-IN')}`};
const pct=(n)=>`${Number(n).toFixed(1)}%`;
const toast=(m)=>{const t=qs('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const val=(id)=>Number(qs(id).value);
function showPage(id){qsa('.page').forEach(p=>p.classList.toggle('active',p.id===id));qsa('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===id));const titles={home:'Your financial life, at a glance',goals:'Plan the life you want',fire:'Build your path to financial freedom',dreams:'Spend on dreams without losing tomorrow'};qs('#page-title').textContent=titles[id]||'LifeMoney';window.scrollTo({top:0,behavior:'smooth'})}
qsa('[data-section]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.section)));qsa('[data-jump]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.jump)));
qsa('.dream-chips button').forEach(b=>b.addEventListener('click',()=>{qs('#afford-price').value=b.dataset.price;toast('Dream cost loaded')}));
const h=new Date().getHours();qs('#greeting').textContent=h<12?'Good morning':h<17?'Good afternoon':'Good evening';
async function api(path,body){const r=await fetch(API_BASE+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.detail?JSON.stringify(d.detail):`Request failed (${r.status})`)}return r.json()}
async function health(){try{const r=await fetch(API_BASE+'/health',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();const p=qs('#api-status');p.classList.add('online');p.innerHTML=`<span class="dot"></span>Cloud live · v${d.version}`;}catch{qs('#api-status').innerHTML='<span class="dot"></span>Cloud unavailable'}}health();
function busy(form,on){form.classList.toggle('loading',on);const b=form.querySelector('button[type=submit]');if(b){if(on){b.dataset.old=b.textContent;b.textContent='Calculating…'}else if(b.dataset.old)b.textContent=b.dataset.old}}
qs('#goal-form').addEventListener('submit',async(e)=>{e.preventDefault();busy(e.currentTarget,true);try{const d=await api('/v1/goals/calculate',{current_cost:val('#goal-cost'),years:val('#goal-years'),inflation_rate:val('#goal-inflation')/100,annual_return:val('#goal-return')/100,current_corpus:val('#goal-corpus'),annual_step_up:val('#goal-step')/100});qs('#goal-result').innerHTML=`<span class="result-kicker">LIVE CLOUD CALCULATION</span><h3>Your goal needs ${money(d.future_cost)}</h3><p>That is the inflation-adjusted target based on the assumptions you entered.</p><div class="result-hero"><span class="label">STARTING SIP WITH ANNUAL STEP-UP</span><strong>${money(d.monthly_sip_step_up)} / mo</strong></div><div class="result-stats"><div class="result-stat"><span>Flat monthly SIP</span><b>${money(d.monthly_sip_flat)}</b></div><div class="result-stat"><span>Goal inflation</span><b>${pct(val('#goal-inflation'))}</b></div><div class="result-stat"><span>Current mapped corpus</span><b>${money(val('#goal-corpus'))}</b></div><div class="result-stat"><span>Years remaining</span><b>${val('#goal-years')}</b></div></div><p class="muted" style="margin-top:18px;font-size:11px">Returns are assumptions, not guarantees. Use conservative scenarios for important goals.</p>`}catch(err){toast('Goal calculation failed');console.error(err)}finally{busy(e.currentTarget,false)}});
qs('#fire-form').addEventListener('submit',async(e)=>{e.preventDefault();busy(e.currentTarget,true);try{const d=await api('/v1/retirement/simulate',{current_age:val('#fire-age'),retirement_age:val('#fire-retire'),life_expectancy:val('#fire-life'),current_monthly_expense:val('#fire-expense'),current_corpus:val('#fire-corpus'),annual_inflation:val('#fire-inflation')/100,pre_retirement_return:val('#fire-pre')/100,post_retirement_return:val('#fire-post')/100,monthly_investment:val('#fire-invest'),annual_step_up:val('#fire-step')/100});const ok=d.survives_to_life_expectancy;qs('#fire-result').innerHTML=`<span class="result-kicker">RETIREMENT ENGINE</span><h3>${ok?'Your plan survives the full horizon':'Your corpus needs reinforcement'}</h3><p>${ok?'Under these assumptions, the simulated corpus remains positive through your selected life expectancy.':'The simulated corpus depletes before the selected life expectancy.'}</p><div class="result-hero ${ok?'success':'warning'}"><span class="label">PROJECTED CORPUS AT RETIREMENT</span><strong>${money(d.projected_corpus_at_retirement)}</strong></div><div class="result-stats"><div class="result-stat"><span>Expense at retirement</span><b>${money(d.expense_at_retirement_monthly)}/mo</b></div><div class="result-stat"><span>Years to retirement</span><b>${d.years_to_retirement}</b></div><div class="result-stat"><span>Corpus at age ${val('#fire-life')}</span><b>${money(d.corpus_at_life_expectancy)}</b></div><div class="result-stat"><span>Depletion age</span><b>${d.depletion_age??'Not depleted'}</b></div></div><p class="muted" style="margin-top:18px;font-size:11px">This is deterministic scenario modelling. Monte Carlo probability is planned for a later release.</p>`}catch(err){toast('FIRE simulation failed');console.error(err)}finally{busy(e.currentTarget,false)}});
qs('#afford-form').addEventListener('submit',async(e)=>{e.preventDefault();busy(e.currentTarget,true);try{const d=await api('/v1/affordability/check',{purchase_price:val('#afford-price'),current_liquid_corpus:val('#afford-liquid'),protected_reserve:val('#afford-reserve'),monthly_surplus:val('#afford-surplus'),annual_return:val('#afford-return')/100,horizon_years:val('#afford-horizon')});const ok=d.affordable_now;const months=d.months_to_afford_without_touching_reserve;qs('#afford-result').innerHTML=`<span class="result-kicker">AFFORDABILITY ENGINE</span><h3>${ok?'Yes — affordable without touching your reserve':'Not yet — protect your reserve first'}</h3><p>${ok?'The purchase fits inside your currently available liquid pool after protecting the reserve.':'Your current liquid pool is insufficient after preserving the protected reserve.'}</p><div class="result-hero ${ok?'success':'warning'}"><span class="label">${ok?'INVESTABLE MONEY LEFT AFTER PURCHASE':'TIME TO AFFORD WITHOUT TOUCHING RESERVE'}</span><strong>${ok?money(d.investable_after_purchase):(months==null?'No surplus':`${months} months`)}</strong></div><div class="result-stats"><div class="result-stat"><span>10-year / selected-horizon opportunity cost</span><b>${money(d.opportunity_cost_at_horizon)}</b></div><div class="result-stat"><span>If you buy now</span><b>${money(d.future_value_if_bought_now)}</b></div><div class="result-stat"><span>If you don't buy</span><b>${money(d.future_value_if_not_bought)}</b></div><div class="result-stat"><span>Protected reserve</span><b>${money(val('#afford-reserve'))}</b></div></div><p class="muted" style="margin-top:18px;font-size:11px">This checks liquidity and opportunity cost. Cross-goal impact analysis comes next.</p>`}catch(err){toast('Affordability check failed');console.error(err)}finally{busy(e.currentTarget,false)}});